apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: my-react-app:1.0.1 # Use the local image built in Minikube
        imagePullPolicy: Never     # Prevent Kubernetes from pulling the image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
